// Generated by scripts/generate-native-contract.mjs from Mercur's native route map.
// Native routes use compiled package declarations, never backend TypeScript source.
// Regenerate with bun run generate:native-contract; do not hand-edit.

export type NativeRoutes = {
    auth: {
        $actorType: {
            $authProvider: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/route") & {
                callback: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/callback/route");
                register: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/register/route");
                resetPassword: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/reset-password/route");
                update: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/update/route");
            };
        };
        mfa: {
            challenges: {
                $id: {
                    verify: typeof import("@medusajs/medusa/api/auth/mfa/challenges/[id]/verify/route");
                };
            };
            factors: typeof import("@medusajs/medusa/api/auth/mfa/factors/route") & {
                $id: typeof import("@medusajs/medusa/api/auth/mfa/factors/[id]/route") & {
                    verify: typeof import("@medusajs/medusa/api/auth/mfa/factors/[id]/verify/route");
                };
            };
            recoveryCodes: typeof import("@medusajs/medusa/api/auth/mfa/recovery-codes/route");
        };
        session: typeof import("@medusajs/medusa/api/auth/session/route");
        token: {
            refresh: typeof import("@medusajs/medusa/api/auth/token/refresh/route");
        };
        verification: {
            confirm: typeof import("@medusajs/medusa/api/auth/verification/confirm/route");
            request: typeof import("@medusajs/medusa/api/auth/verification/request/route");
        };
    };
    store: {
        carts: typeof import("@medusajs/medusa/api/store/carts/route") & {
            $id: typeof import("@medusajs/medusa/api/store/carts/[id]/route") & {
                complete: typeof import("@mercurjs/core/api/store/carts/[id]/complete/route");
                customer: typeof import("@medusajs/medusa/api/store/carts/[id]/customer/route");
                lineItems: typeof import("@mercurjs/core/api/store/carts/[id]/line-items/route") & {
                    $lineId: typeof import("@medusajs/medusa/api/store/carts/[id]/line-items/[line_id]/route");
                };
                promotions: typeof import("@mercurjs/core/api/store/carts/[id]/promotions/route");
                shippingMethods: typeof import("@mercurjs/core/api/store/carts/[id]/shipping-methods/route");
                taxes: typeof import("@medusajs/medusa/api/store/carts/[id]/taxes/route");
            };
        };
        collections: typeof import("@medusajs/medusa/api/store/collections/route") & {
            $id: typeof import("@medusajs/medusa/api/store/collections/[id]/route");
        };
        currencies: typeof import("@medusajs/medusa/api/store/currencies/route") & {
            $code: typeof import("@medusajs/medusa/api/store/currencies/[code]/route");
        };
        customers: typeof import("@medusajs/medusa/api/store/customers/route") & {
            me: typeof import("@medusajs/medusa/api/store/customers/me/route") & {
                addresses: typeof import("@medusajs/medusa/api/store/customers/me/addresses/route") & {
                    $addressId: typeof import("@medusajs/medusa/api/store/customers/me/addresses/[address_id]/route");
                };
            };
        };
        locales: typeof import("@medusajs/medusa/api/store/locales/route");
        offers: typeof import("@mercurjs/core/api/store/offers/route") & {
            $id: typeof import("@mercurjs/core/api/store/offers/[id]/route");
        };
        orderGroups: typeof import("@mercurjs/core/api/store/order-groups/route") & {
            $id: typeof import("@mercurjs/core/api/store/order-groups/[id]/route");
        };
        orders: typeof import("@mercurjs/core/api/store/orders/route") & {
            $id: typeof import("@mercurjs/core/api/store/orders/[id]/route") & {
                transfer: {
                    accept: typeof import("@medusajs/medusa/api/store/orders/[id]/transfer/accept/route");
                    cancel: typeof import("@medusajs/medusa/api/store/orders/[id]/transfer/cancel/route");
                    decline: typeof import("@medusajs/medusa/api/store/orders/[id]/transfer/decline/route");
                    request: typeof import("@medusajs/medusa/api/store/orders/[id]/transfer/request/route");
                };
            };
        };
        paymentCollections: typeof import("@medusajs/medusa/api/store/payment-collections/route") & {
            $id: {
                paymentSessions: typeof import("@medusajs/medusa/api/store/payment-collections/[id]/payment-sessions/route");
            };
        };
        paymentProviders: typeof import("@medusajs/medusa/api/store/payment-providers/route");
        productAttributes: typeof import("@mercurjs/core/api/store/product-attributes/route") & {
            $id: typeof import("@mercurjs/core/api/store/product-attributes/[id]/route");
        };
        productCategories: typeof import("@mercurjs/core/api/store/product-categories/route") & {
            $id: typeof import("@mercurjs/core/api/store/product-categories/[id]/route");
        };
        productOptions: typeof import("@medusajs/medusa/api/store/product-options/route") & {
            $id: typeof import("@medusajs/medusa/api/store/product-options/[id]/route");
        };
        productTags: typeof import("@medusajs/medusa/api/store/product-tags/route") & {
            $id: typeof import("@medusajs/medusa/api/store/product-tags/[id]/route");
        };
        productTypes: typeof import("@medusajs/medusa/api/store/product-types/route") & {
            $id: typeof import("@medusajs/medusa/api/store/product-types/[id]/route");
        };
        productVariants: typeof import("@medusajs/medusa/api/store/product-variants/route") & {
            $id: typeof import("@medusajs/medusa/api/store/product-variants/[id]/route");
        };
        products: typeof import("@mercurjs/core/api/store/products/route") & {
            $id: typeof import("@mercurjs/core/api/store/products/[id]/route");
        };
        regions: typeof import("@medusajs/medusa/api/store/regions/route") & {
            $id: typeof import("@medusajs/medusa/api/store/regions/[id]/route");
        };
        returnReasons: typeof import("@medusajs/medusa/api/store/return-reasons/route") & {
            $id: typeof import("@medusajs/medusa/api/store/return-reasons/[id]/route");
        };
        returns: typeof import("@medusajs/medusa/api/store/returns/route");
        sellers: typeof import("@mercurjs/core/api/store/sellers/route") & {
            $id: typeof import("@mercurjs/core/api/store/sellers/[id]/route");
        };
        shippingOptions: typeof import("@mercurjs/core/api/store/shipping-options/route") & {
            $id: {
                calculate: typeof import("@medusajs/medusa/api/store/shipping-options/[id]/calculate/route");
            };
        };
        reviews: typeof import("@mercurjs/core/api/store/reviews/route") & {
            $id: typeof import("@mercurjs/core/api/store/reviews/[id]/route");
        };
    };
};
