import Image from "next/image"
import Link from "next/link"

import { publicDidarProducts } from "@/lib/didar/public-catalog"
import { type DidarLocale } from "@/lib/helpers/storefront-locale"

const homeText = {
  fa: { kicker: "پلتفرم طلا و جواهر دیدار", headline: "جهان طلا، از دریچهٔ دیدار.", enter: "ورود به بازار جواهرات", verify: "اصالت‌سنجی", verifyNote: "با کد اختصاصی", warranty: "گارانتی دیدار", warrantyNote: "برای قطعات واجد شرایط", buyback: "بازخرید شفاف", buybackNote: "ثبت درخواست", introTag: "دیدار گلد · از مجموعهٔ بهشتی", introTitle: "انتخابی برای نگاه حرفه‌ای شما", intro: "مجموعه‌های طلا و جواهر را ببینید، جزئیات هر قطعه را بررسی کنید و برای سفارش و همکاری با ما در ارتباط باشید.", explore: "کشف محصولات", world: "جهان جواهرات دیدار", find: "قطعهٔ خود را پیدا کنید.", categories: ["گردنبند و پلاک", "دستبند و بنگل", "انگشتر", "گوشواره", "ساعت"], editorial: "نور، شکل می‌گیرد.", editorialNote: "نیم‌ست نورا، از مجموعهٔ دیدار گلد.", viewNoura: "مشاهدهٔ نورا", worlds: "دنیای دیدار گلد", types: ["طلای روزمره", "طلای لوکس روزمره", "طلای لوکس", "ساعت طلا"], view: "مشاهدهٔ محصولات", narrative: "روایت دیدار", life: "جواهر، در زندگی.", discover: "کشف مجموعهٔ دیدار", collections: "کالکشن‌های دیدار", collectionNames: ["کالکشن عروس", "دیدار گلد", "سیلون گلد"], soon: "به‌زودی", details: "ظرافت، در هر جزئیات", parnian: "مشاهدهٔ پرنیان", showroomTag: "شوروم پلتفرم دیدار گلد", showroom: "فرصتی برای دیدن. فضایی برای همکاری.", showroomText: "دیدار، نقطهٔ اتصال برندها، تولیدکنندگان و همکاران صنف طلا و جواهر است.", services: ["گفت‌وگو با مشاور", "خدمات ما", "دیدار با دیدار گلد"], contact: "تماس با ما", serviceCta: "بیشتر بدانید" },
  ar: { kicker: "منصة ديدار للمجوهرات", headline: "عالم الذهب من منظور ديدار.", enter: "استكشف المجوهرات", verify: "التحقق من الأصالة", verifyNote: "برمز خاص", warranty: "ضمان ديدار", warrantyNote: "للقطع المؤهلة", buyback: "إعادة الشراء", buybackNote: "إرسال طلب", introTag: "ديدار جولد", introTitle: "اختيار يليق بذوقك", intro: "اكتشف مجموعات الذهب والمجوهرات وتفاصيل كل قطعة.", explore: "اكتشف المنتجات", world: "عالم مجوهرات ديدار", find: "اعثر على قطعتك.", categories: ["قلائد", "أساور", "خواتم", "أقراط", "ساعات"], editorial: "النور يتشكل.", editorialNote: "مجموعة نورا من ديدار.", viewNoura: "عرض نورا", worlds: "عوالم ديدار", types: ["ذهب يومي", "فاخر يومي", "ذهب فاخر", "ساعات ذهبية"], view: "عرض المنتجات", narrative: "قصة ديدار", life: "المجوهرات في الحياة.", discover: "اكتشف المجموعة", collections: "مجموعات ديدار", collectionNames: ["مجموعة العروس", "ديدار جولد", "سيلون جولد"], soon: "قريباً", details: "أناقة في كل التفاصيل", parnian: "عرض برنيان", showroomTag: "صالة ديدار", showroom: "مساحة للقاء والتعاون.", showroomText: "ديدار يجمع العلامات وصناع الذهب وشركاء السوق.", services: ["تحدث إلى مستشار", "خدماتنا", "زر ديدار"], contact: "اتصل بنا", serviceCta: "اعرف المزيد" },
  en: { kicker: "Didar Gold jewellery platform", headline: "The world of gold, through Didar.", enter: "Enter the jewellery world", verify: "Verify authenticity", verifyNote: "With a unique code", warranty: "Didar warranty", warrantyNote: "For eligible pieces", buyback: "Transparent buyback", buybackNote: "Submit a request", introTag: "Didar Gold · By Beheshti", introTitle: "A choice for the discerning eye", intro: "Explore our jewellery collections, study every detail and get in touch about orders and collaboration.", explore: "Discover the creations", world: "The world of Didar jewellery", find: "Find your piece.", categories: ["Necklaces", "Bracelets", "Rings", "Earrings", "Watches"], editorial: "Light takes shape.", editorialNote: "Noura from Didar Gold.", viewNoura: "View Noura", worlds: "The Didar world", types: ["Everyday gold", "Everyday luxury", "Fine gold", "Gold watches"], view: "Explore creations", narrative: "The Didar story", life: "Jewellery in life.", discover: "Discover Didar", collections: "Didar collections", collectionNames: ["Bridal collection", "Didar Gold", "Silon Gold"], soon: "Coming soon", details: "Beauty in every detail", parnian: "View Parnian", showroomTag: "Didar showroom", showroom: "A place to meet. A place to collaborate.", showroomText: "Didar connects brands, makers and partners in the jewellery world.", services: ["Speak with an adviser", "Our services", "Visit Didar"], contact: "Contact us", serviceCta: "Learn more" },
  fr: { kicker: "La plateforme de bijoux Didar Gold", headline: "Le monde de l’or, vu par Didar.", enter: "Explorer la joaillerie", verify: "Vérifier l’authenticité", verifyNote: "Avec un code unique", warranty: "Garantie Didar", warrantyNote: "Pour les pièces éligibles", buyback: "Rachat transparent", buybackNote: "Faire une demande", introTag: "Didar Gold · Par Beheshti", introTitle: "Pour les regards exigeants", intro: "Découvrez les collections et chaque détail des créations Didar.", explore: "Découvrir les créations", world: "L’univers des bijoux Didar", find: "Trouvez votre pièce.", categories: ["Colliers", "Bracelets", "Bagues", "Boucles d’oreilles", "Montres"], editorial: "La lumière prend forme.", editorialNote: "Noura, par Didar Gold.", viewNoura: "Voir Noura", worlds: "L’univers Didar", types: ["Or au quotidien", "Luxe quotidien", "Or de luxe", "Montres en or"], view: "Voir les créations", narrative: "L’histoire Didar", life: "Le bijou dans la vie.", discover: "Découvrir Didar", collections: "Collections Didar", collectionNames: ["Collection mariée", "Didar Gold", "Silon Gold"], soon: "À venir", details: "L’élégance en détail", parnian: "Voir Parnian", showroomTag: "Showroom Didar", showroom: "Un espace de rencontres et de collaboration.", showroomText: "Didar réunit marques, artisans et partenaires de la joaillerie.", services: ["Parler à un conseiller", "Nos services", "Visiter Didar"], contact: "Nous contacter", serviceCta: "En savoir plus" },
} as const

const categoryImages = ["MAL-01/1.webp", "MAL-18/3.webp", "MAL-01/1.webp", "MAL-01/1.webp", "WATCH-01/1.webp"]
const worldImages = ["TRSH-01/1.webp", "MAL-01/1.webp", "SET-666/f9ba07ef.webp", "WATCH-01/1.webp"]
const collectionImages = ["campaign-ellipse.png", "showroom-concept.png", "campaign-pearl.png"]

export function DidarReferenceHome({ locale }: { locale: DidarLocale }) {
  const t = homeText[locale]
  const rtl = locale === "fa" || locale === "ar"
  const featured = publicDidarProducts.slice(0, 6)
  return <main className="didar-site didar-reference-home" lang={locale} dir={rtl ? "rtl" : "ltr"}>
    <section className="didar-film" aria-label={t.kicker}>
      <video className="didar-film-video" autoPlay muted loop playsInline preload="metadata" poster="https://didargold.ir/assets/film/didar-portrait-v7.webp"><source src="https://didargold.ir/assets/film/didar-fullscreen-v8.mp4" type="video/mp4" /></video>
      <div className="didar-film-caption"><p>{t.kicker}</p><h1>{t.headline}</h1><Link href={`/${locale}/jewellery`}>{t.enter}</Link></div>
    </section>
    <div className="didar-rates" aria-label={locale === "fa" ? "نرخ‌های مرجع بازار" : "Market reference rates"}>{["اونس جهانی", "گرم طلای ۱۸ عیار", "مثقال بازار", "سکه امامی"].map((name) => <span key={name}>{name} <strong>{locale === "fa" ? "دریافت نرخ…" : "Rate pending…"}</strong></span>)}</div>
    <section className="didar-trust" aria-label={t.verify}><Link href={`/${locale}/my-didar/consumer/authenticity`}><strong>{t.verify}</strong><span>{t.verifyNote}</span></Link><Link href={`/${locale}/my-didar/consumer/warranty`}><strong>{t.warranty}</strong><span>{t.warrantyNote}</span></Link><Link href={`/${locale}/my-didar/consumer/buyback`}><strong>{t.buyback}</strong><span>{t.buybackNote}</span></Link></section>
    <section className="didar-reference-intro"><p className="didar-reference-kicker">{t.introTag}</p><h2>{t.introTitle}</h2><p>{t.intro}</p><Link href={`/${locale}/jewellery`}>{t.explore} ↗</Link></section>
    <section className="didar-reference-section"><header><h2>{t.world}</h2><p>{t.find}</p></header><div className="didar-category-rail">{t.categories.map((name, index) => <Link key={name} href={`/${locale}/jewellery${index === 4 ? "?q=ساعت" : ""}`}><Image src={`https://didargold.ir/media/products/${categoryImages[index]}`} alt="" fill sizes="(max-width: 720px) 55vw, 20vw" /><h3>{name}</h3></Link>)}</div></section>
    <section className="didar-reference-section didar-featured" aria-label={t.explore}><div className="didar-featured-grid">{featured.map((item) => <article key={item.slug}><Link href={`/${locale}/creation/${item.slug}`}><div><Image src={item.image} alt={item.title} fill sizes="(max-width: 720px) 48vw, 17vw" /></div><h3 lang="fa" dir="rtl">{item.title}</h3><p>{locale === "fa" ? "برای مشاهدهٔ مشخصات وارد شوید · طلای ۱۸ عیار" : "18k gold · details on request"}</p></Link></article>)}</div></section>
    <section className="didar-editorial"><Image src="https://didargold.ir/assets/editorial/noura.png" alt="" fill sizes="100vw" /><div><h2>{t.editorial}</h2><p>{t.editorialNote}</p><Link href={`/${locale}/creation/malachite-seyfi-1`}>{t.viewNoura} ↗</Link></div></section>
    <section className="didar-reference-section"><header><h2>{t.worlds}</h2></header><div className="didar-world-grid">{t.types.map((name, index) => <Link key={name} href={`/${locale}/jewellery${index === 0 ? `?category=${encodeURIComponent("طلای روزمره")}` : index === 1 ? `?category=${encodeURIComponent("طلای لوکس روزمره")}` : index === 3 ? "?q=ساعت" : ""}`}><Image src={`https://didargold.ir/media/products/${worldImages[index]}`} alt="" fill sizes="(max-width: 720px) 50vw, 25vw" /><h3>{name}</h3><span>{t.view} ↗</span></Link>)}</div></section>
    <section className="didar-editorial didar-life" id="story"><Image src="https://didargold.ir/assets/didar-campaign.webp" alt="" fill sizes="100vw" /><div><p>{t.narrative}</p><h2>{t.life}</h2><Link href={`/${locale}/jewellery`}>{t.discover} ↗</Link></div></section>
    <section className="didar-reference-section" id="collections"><header><h2>{t.collections}</h2></header><div className="didar-collection-tiles">{t.collectionNames.map((name, index) => <Link key={name} href={`/${locale}/jewellery`}><Image src={`https://didargold.ir/assets/${collectionImages[index]}`} alt="" fill sizes="(max-width: 720px) 85vw, 33vw" /><div><h3>{name}</h3><span>{index === 1 ? t.soon : t.view} ↗</span></div></Link>)}</div></section>
    <section className="didar-editorial didar-parnian"><Image src="https://didargold.ir/assets/editorial/parnian.png" alt="" fill sizes="100vw" /><div><h2>{t.details}</h2><Link href={`/${locale}/creation/malachite-seyfi-18`}>{t.parnian} ↗</Link></div></section>
    <section className="didar-showroom" id="showroom"><div><p>{t.showroomTag}</p><h2>{t.showroom}</h2><p>{t.showroomText}</p><Link href={`/${locale}/my-didar`}>{t.contact} ↗</Link></div><Image src="https://didargold.ir/assets/showroom-concept.png" alt="" width={1000} height={900} sizes="(max-width: 720px) 100vw, 55vw" /></section>
    <section className="didar-contact-tiles">{t.services.map((title, index) => <article key={title}><h3>{title}</h3><p>{index === 0 ? "۰۲۱–۵۲۰۰۲۰۵۰" : index === 1 ? t.verifyNote : t.showroomText}</p><Link href={index === 1 ? `/${locale}/my-didar` : `/${locale}#contact`}>{index === 1 ? t.serviceCta : t.contact} ↗</Link></article>)}</section>
  </main>
}
