import type { DidarLocale } from "@/lib/helpers/storefront-locale"

export const didarUiCopy = {
  fa: {
    catalog: "زیورآلات دیدار", explore: "مجموعه‌ها را کشف کنید", search: "جست‌وجوی نام محصول",
    filter: "دسته‌بندی", all: "همهٔ محصولات", daily: "طلای روزمره", luxury: "طلای لوکس روزمره",
    uncategorized: "سایر محصولات", results: "محصول", none: "محصولی پیدا نشد", detail: "مشاهدهٔ محصول",
    back: "بازگشت به محصولات", source: "مشاهده در وب‌سایت دیدار", material: "جنس", category: "دسته‌بندی",
    unknown: "در منبع عمومی مشخص نشده", detailsNote: "اطلاعات وزن، قیمت، اجرت و موجودی پس از تأیید دادهٔ تجاری نمایش داده می‌شود.",
    galleryNote: "گالری این محصول هنوز بررسی نشده است.", myDidar: "مای دیدار", gateway: "چطور با دیدار همراه می‌شوید؟",
    gatewayIntro: "مسیر خود را انتخاب کنید تا خدمات متناسب با شما را ببینید.",
    consumer: "مشتری دیدار", retailer: "خرده‌فروش", supplier: "تأمین‌کننده و تولیدکننده", wholesaler: "بنکدار",
    consumerServices: ["فروشگاه‌یاب", "شناسنامه و اصالت", "گارانتی و خدمات", "بازخرید"],
    retailerServices: ["پروندهٔ همکاری", "ویترین محصول", "استعلام و درخواست", "پیگیری سفارش"],
    supplierServices: ["پروندهٔ تأمین‌کننده", "پیشنهاد محصول", "بررسی و انتشار", "پیگیری عرضه"],
    wholesalerServices: ["پروندهٔ بنکداری", "همکاری تجاری", "پیگیری درخواست"],
    serviceNote: "این بخش نمای مسیر خدمات است. ثبت و پیگیری واقعی هر خدمت با اتصال حساب و فرایند سروری فعال می‌شود.",
    serviceState: "در حال طراحی و اتصال", viewServices: "مشاهدهٔ مسیر خدمات",
  },
  en: {
    catalog: "Didar jewellery", explore: "Discover the collection", search: "Search product names",
    filter: "Category", all: "All products", daily: "Everyday gold", luxury: "Everyday luxury gold",
    uncategorized: "Other products", results: "products", none: "No products found", detail: "View product",
    back: "Back to products", source: "See on DidarGold", material: "Material", category: "Category",
    unknown: "Not stated publicly", detailsNote: "Weight, price, premium and availability appear after verified commercial data is available.",
    galleryNote: "This product's gallery has not been reviewed yet.", myDidar: "My Didar", gateway: "How will you use Didar?",
    gatewayIntro: "Choose your path to explore the relevant services.",
    consumer: "Didar customer", retailer: "Retailer", supplier: "Supplier and maker", wholesaler: "Wholesaler",
    consumerServices: ["Find a store", "Identity and authenticity", "Warranty and care", "Buyback"],
    retailerServices: ["Business application", "Product showcase", "Inquiries", "Order tracking"],
    supplierServices: ["Supplier profile", "Product proposals", "Review and publication", "Supply tracking"],
    wholesalerServices: ["Wholesale application", "Business cooperation", "Request tracking"],
    serviceNote: "This page shows the service paths. Live submissions and tracking become available as accounts and server flows are connected.",
    serviceState: "Design and integration in progress", viewServices: "Explore services",
  },
  ar: {
    catalog: "مجوهرات ديدار", explore: "اكتشف التشكيلة", search: "ابحث باسم المنتج",
    filter: "الفئة", all: "كل المنتجات", daily: "ذهب يومي", luxury: "ذهب فاخر يومي",
    uncategorized: "منتجات أخرى", results: "منتج", none: "لم نعثر على منتجات", detail: "عرض المنتج",
    back: "العودة إلى المنتجات", source: "عرضه على موقع ديدار", material: "المادة", category: "الفئة",
    unknown: "غير مذكور علنًا", detailsNote: "يظهر الوزن والسعر والأجور والتوفر بعد اعتماد البيانات التجارية.",
    galleryNote: "لم تُراجع صور هذا المنتج بعد.", myDidar: "ديدار الخاص بي", gateway: "كيف تود استخدام ديدار؟",
    gatewayIntro: "اختر مسارك لاستكشاف الخدمات المناسبة لك.",
    consumer: "عميل ديدار", retailer: "تاجر تجزئة", supplier: "مورّد ومصنّع", wholesaler: "تاجر جملة",
    consumerServices: ["البحث عن متجر", "هوية المنتج وأصالته", "الضمان والخدمة", "إعادة الشراء"],
    retailerServices: ["طلب التعاون", "عرض المنتجات", "الاستفسارات والطلبات", "تتبع الطلب"],
    supplierServices: ["ملف المورّد", "اقتراح منتج", "المراجعة والنشر", "تتبع التوريد"],
    wholesalerServices: ["ملف الجملة", "التعاون التجاري", "متابعة الطلبات"],
    serviceNote: "هذه الصفحة تعرض مسارات الخدمات. يصبح التسجيل والمتابعة متاحين عند ربط الحسابات والإجراءات الخلفية.",
    serviceState: "قيد التصميم والربط", viewServices: "استكشف الخدمات",
  },
  fr: {
    catalog: "Bijoux Didar", explore: "Découvrir la collection", search: "Rechercher un produit",
    filter: "Catégorie", all: "Tous les produits", daily: "Or du quotidien", luxury: "Or précieux du quotidien",
    uncategorized: "Autres produits", results: "produits", none: "Aucun produit trouvé", detail: "Voir le produit",
    back: "Retour aux produits", source: "Voir sur DidarGold", material: "Matière", category: "Catégorie",
    unknown: "Non précisé publiquement", detailsNote: "Poids, prix, façon et disponibilité s'afficheront après validation des données commerciales.",
    galleryNote: "La galerie de ce produit n'a pas encore été vérifiée.", myDidar: "Mon Didar", gateway: "Comment souhaitez-vous utiliser Didar ?",
    gatewayIntro: "Choisissez votre parcours pour découvrir les services adaptés.",
    consumer: "Client Didar", retailer: "Détaillant", supplier: "Fournisseur et fabricant", wholesaler: "Grossiste",
    consumerServices: ["Trouver une boutique", "Identité et authenticité", "Garantie et entretien", "Rachat"],
    retailerServices: ["Demande de partenariat", "Catalogue", "Demandes et devis", "Suivi des commandes"],
    supplierServices: ["Profil fournisseur", "Propositions de produits", "Validation et publication", "Suivi de l'offre"],
    wholesalerServices: ["Profil grossiste", "Coopération commerciale", "Suivi des demandes"],
    serviceNote: "Cette page présente les parcours. Les demandes et suivis seront actifs après connexion des comptes et services.",
    serviceState: "Conception et intégration en cours", viewServices: "Découvrir les services",
  },
} satisfies Record<DidarLocale, Record<string, string | string[]>>
