// Generated by shared/p01/generate-native-contract.mjs from native Mercur routes.
// Resolve compiled native declarations; never import backend implementation source.
export type NativeRoutes = {
    admin: {
        apiKeys: typeof import("@medusajs/medusa/api/admin/api-keys/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/api-keys/[id]/route") & {
                revoke: typeof import("@medusajs/medusa/api/admin/api-keys/[id]/revoke/route");
                salesChannels: typeof import("@medusajs/medusa/api/admin/api-keys/[id]/sales-channels/route");
            };
        };
        campaigns: typeof import("@medusajs/medusa/api/admin/campaigns/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/campaigns/[id]/route") & {
                promotions: typeof import("@medusajs/medusa/api/admin/campaigns/[id]/promotions/route");
            };
        };
        claims: typeof import("@medusajs/medusa/api/admin/claims/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/claims/[id]/route") & {
                cancel: typeof import("@medusajs/medusa/api/admin/claims/[id]/cancel/route");
                claimItems: typeof import("@medusajs/medusa/api/admin/claims/[id]/claim-items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/claim-items/[action_id]/route");
                };
                inbound: {
                    items: typeof import("@medusajs/medusa/api/admin/claims/[id]/inbound/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/inbound/items/[action_id]/route");
                    };
                    shippingMethod: typeof import("@medusajs/medusa/api/admin/claims/[id]/inbound/shipping-method/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/inbound/shipping-method/[action_id]/route");
                    };
                };
                outbound: {
                    items: typeof import("@mercurjs/core/api/admin/claims/[id]/outbound/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/outbound/items/[action_id]/route");
                    };
                    shippingMethod: typeof import("@medusajs/medusa/api/admin/claims/[id]/outbound/shipping-method/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/claims/[id]/outbound/shipping-method/[action_id]/route");
                    };
                };
                request: typeof import("@mercurjs/core/api/admin/claims/[id]/request/route");
            };
        };
        collections: typeof import("@mercurjs/core/api/admin/collections/route") & {
            $id: typeof import("@mercurjs/core/api/admin/collections/[id]/route") & {
                products: typeof import("@medusajs/medusa/api/admin/collections/[id]/products/route");
            };
        };
        commissionRates: typeof import("@mercurjs/core/api/admin/commission-rates/route") & {
            $id: typeof import("@mercurjs/core/api/admin/commission-rates/[id]/route") & {
                rules: typeof import("@mercurjs/core/api/admin/commission-rates/[id]/rules/route");
            };
        };
        currencies: typeof import("@medusajs/medusa/api/admin/currencies/route") & {
            $code: typeof import("@medusajs/medusa/api/admin/currencies/[code]/route");
        };
        customerGroups: typeof import("@medusajs/medusa/api/admin/customer-groups/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/customer-groups/[id]/route") & {
                customers: typeof import("@medusajs/medusa/api/admin/customer-groups/[id]/customers/route");
            };
        };
        customers: typeof import("@medusajs/medusa/api/admin/customers/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/customers/[id]/route") & {
                addresses: typeof import("@medusajs/medusa/api/admin/customers/[id]/addresses/route") & {
                    $addressId: typeof import("@medusajs/medusa/api/admin/customers/[id]/addresses/[address_id]/route");
                };
                customerGroups: typeof import("@medusajs/medusa/api/admin/customers/[id]/customer-groups/route");
            };
        };
        draftOrders: typeof import("@medusajs/medusa/api/admin/draft-orders/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/route") & {
                convertToOrder: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/convert-to-order/route");
                edit: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/route") & {
                    confirm: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/confirm/route");
                    items: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/items/[action_id]/route");
                        item: {
                            $itemId: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/items/item/[item_id]/route");
                        };
                    };
                    promotions: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/promotions/route");
                    request: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/request/route");
                    shippingMethods: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/shipping-methods/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/shipping-methods/[action_id]/route");
                        method: {
                            $methodId: typeof import("@medusajs/medusa/api/admin/draft-orders/[id]/edit/shipping-methods/method/[method_id]/route");
                        };
                    };
                };
            };
        };
        exchanges: typeof import("@medusajs/medusa/api/admin/exchanges/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/route") & {
                cancel: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/cancel/route");
                inbound: {
                    items: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/inbound/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/inbound/items/[action_id]/route");
                    };
                    shippingMethod: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/inbound/shipping-method/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/inbound/shipping-method/[action_id]/route");
                    };
                };
                outbound: {
                    items: typeof import("@mercurjs/core/api/admin/exchanges/[id]/outbound/items/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/outbound/items/[action_id]/route");
                    };
                    shippingMethod: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/outbound/shipping-method/route") & {
                        $actionId: typeof import("@medusajs/medusa/api/admin/exchanges/[id]/outbound/shipping-method/[action_id]/route");
                    };
                };
                request: typeof import("@mercurjs/core/api/admin/exchanges/[id]/request/route");
            };
        };
        featureFlags: typeof import("@medusajs/medusa/api/admin/feature-flags/route");
        fulfillmentProviders: typeof import("@medusajs/medusa/api/admin/fulfillment-providers/route") & {
            $id: {
                options: typeof import("@medusajs/medusa/api/admin/fulfillment-providers/[id]/options/route");
            };
        };
        fulfillmentSets: {
            $id: typeof import("@medusajs/medusa/api/admin/fulfillment-sets/[id]/route") & {
                serviceZones: typeof import("@medusajs/medusa/api/admin/fulfillment-sets/[id]/service-zones/route") & {
                    $zoneId: typeof import("@medusajs/medusa/api/admin/fulfillment-sets/[id]/service-zones/[zone_id]/route");
                };
            };
        };
        fulfillments: typeof import("@medusajs/medusa/api/admin/fulfillments/route") & {
            $id: {
                cancel: typeof import("@medusajs/medusa/api/admin/fulfillments/[id]/cancel/route");
                shipment: typeof import("@medusajs/medusa/api/admin/fulfillments/[id]/shipment/route");
            };
        };
        index: {
            details: typeof import("@medusajs/medusa/api/admin/index/details/route");
            sync: typeof import("@medusajs/medusa/api/admin/index/sync/route");
        };
        inventoryItems: typeof import("@medusajs/medusa/api/admin/inventory-items/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/inventory-items/[id]/route") & {
                locationLevels: typeof import("@medusajs/medusa/api/admin/inventory-items/[id]/location-levels/route") & {
                    $locationId: typeof import("@medusajs/medusa/api/admin/inventory-items/[id]/location-levels/[location_id]/route");
                    batch: typeof import("@medusajs/medusa/api/admin/inventory-items/[id]/location-levels/batch/route");
                };
            };
            locationLevels: {
                batch: typeof import("@medusajs/medusa/api/admin/inventory-items/location-levels/batch/route");
            };
        };
        invites: typeof import("@medusajs/medusa/api/admin/invites/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/invites/[id]/route") & {
                resend: typeof import("@medusajs/medusa/api/admin/invites/[id]/resend/route");
            };
            accept: typeof import("@medusajs/medusa/api/admin/invites/accept/route");
        };
        layouts: {
            $zone: {
                configuration: typeof import("@medusajs/medusa/api/admin/layouts/[zone]/configuration/route");
            };
            configurations: typeof import("@medusajs/medusa/api/admin/layouts/configurations/route");
        };
        locales: typeof import("@medusajs/medusa/api/admin/locales/route") & {
            $code: typeof import("@medusajs/medusa/api/admin/locales/[code]/route");
        };
        members: typeof import("@mercurjs/core/api/admin/members/route");
        notifications: typeof import("@medusajs/medusa/api/admin/notifications/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/notifications/[id]/route");
        };
        offers: typeof import("@mercurjs/core/api/admin/offers/route") & {
            $id: typeof import("@mercurjs/core/api/admin/offers/[id]/route");
            batch: typeof import("@mercurjs/core/api/admin/offers/batch/route");
        };
        orderChanges: {
            $id: typeof import("@medusajs/medusa/api/admin/order-changes/[id]/route");
        };
        orderEdits: typeof import("@medusajs/medusa/api/admin/order-edits/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/route") & {
                confirm: typeof import("@mercurjs/core/api/admin/order-edits/[id]/confirm/route");
                items: typeof import("@mercurjs/core/api/admin/order-edits/[id]/items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/items/[action_id]/route");
                    item: {
                        $itemId: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/items/item/[item_id]/route");
                    };
                };
                request: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/request/route");
                shippingMethod: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/shipping-method/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/order-edits/[id]/shipping-method/[action_id]/route");
                };
            };
        };
        orderGroups: typeof import("@mercurjs/core/api/admin/order-groups/route") & {
            $id: typeof import("@mercurjs/core/api/admin/order-groups/[id]/route");
        };
        orders: typeof import("@mercurjs/core/api/admin/orders/route") & {
            $id: typeof import("@mercurjs/core/api/admin/orders/[id]/route") & {
                archive: typeof import("@medusajs/medusa/api/admin/orders/[id]/archive/route");
                cancel: typeof import("@medusajs/medusa/api/admin/orders/[id]/cancel/route");
                changes: typeof import("@medusajs/medusa/api/admin/orders/[id]/changes/route");
                commissionLines: typeof import("@mercurjs/core/api/admin/orders/[id]/commission-lines/route");
                complete: typeof import("@medusajs/medusa/api/admin/orders/[id]/complete/route");
                creditLines: typeof import("@medusajs/medusa/api/admin/orders/[id]/credit-lines/route");
                fulfillments: typeof import("@medusajs/medusa/api/admin/orders/[id]/fulfillments/route") & {
                    $fulfillmentId: {
                        cancel: typeof import("@medusajs/medusa/api/admin/orders/[id]/fulfillments/[fulfillment_id]/cancel/route");
                        markAsDelivered: typeof import("@medusajs/medusa/api/admin/orders/[id]/fulfillments/[fulfillment_id]/mark-as-delivered/route");
                        shipments: typeof import("@medusajs/medusa/api/admin/orders/[id]/fulfillments/[fulfillment_id]/shipments/route");
                    };
                };
                lineItems: typeof import("@medusajs/medusa/api/admin/orders/[id]/line-items/route");
                orderGroup: typeof import("@mercurjs/core/api/admin/orders/[id]/order-group/route");
                paymentSessions: {
                    authorize: typeof import("@medusajs/medusa/api/admin/orders/[id]/payment-sessions/authorize/route");
                };
                preview: typeof import("@medusajs/medusa/api/admin/orders/[id]/preview/route");
                shippingOptions: typeof import("@medusajs/medusa/api/admin/orders/[id]/shipping-options/route");
                transfer: typeof import("@medusajs/medusa/api/admin/orders/[id]/transfer/route") & {
                    cancel: typeof import("@medusajs/medusa/api/admin/orders/[id]/transfer/cancel/route");
                };
            };
            export: typeof import("@medusajs/medusa/api/admin/orders/export/route");
        };
        paymentCollections: typeof import("@medusajs/medusa/api/admin/payment-collections/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/payment-collections/[id]/route") & {
                markAsPaid: typeof import("@medusajs/medusa/api/admin/payment-collections/[id]/mark-as-paid/route");
                paymentSessions: typeof import("@medusajs/medusa/api/admin/payment-collections/[id]/payment-sessions/route");
            };
        };
        payments: typeof import("@medusajs/medusa/api/admin/payments/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/payments/[id]/route") & {
                capture: typeof import("@medusajs/medusa/api/admin/payments/[id]/capture/route");
                refund: typeof import("@medusajs/medusa/api/admin/payments/[id]/refund/route");
            };
            paymentProviders: typeof import("@medusajs/medusa/api/admin/payments/payment-providers/route");
        };
        payouts: typeof import("@mercurjs/core/api/admin/payouts/route") & {
            $id: typeof import("@mercurjs/core/api/admin/payouts/[id]/route");
        };
        plugins: typeof import("@medusajs/medusa/api/admin/plugins/route");
        priceLists: typeof import("@medusajs/medusa/api/admin/price-lists/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/price-lists/[id]/route") & {
                prices: typeof import("@medusajs/medusa/api/admin/price-lists/[id]/prices/route") & {
                    batch: typeof import("@medusajs/medusa/api/admin/price-lists/[id]/prices/batch/route");
                };
                products: typeof import("@medusajs/medusa/api/admin/price-lists/[id]/products/route");
            };
        };
        pricePreferences: typeof import("@medusajs/medusa/api/admin/price-preferences/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/price-preferences/[id]/route");
        };
        productAttributes: typeof import("@mercurjs/core/api/admin/product-attributes/route") & {
            $id: typeof import("@mercurjs/core/api/admin/product-attributes/[id]/route") & {
                values: typeof import("@mercurjs/core/api/admin/product-attributes/[id]/values/route") & {
                    $valueId: typeof import("@mercurjs/core/api/admin/product-attributes/[id]/values/[value_id]/route");
                };
            };
        };
        productCategories: typeof import("@mercurjs/core/api/admin/product-categories/route") & {
            $id: typeof import("@mercurjs/core/api/admin/product-categories/[id]/route") & {
                products: typeof import("@mercurjs/core/api/admin/product-categories/[id]/products/route");
                sellers: typeof import("@mercurjs/core/api/admin/product-categories/[id]/sellers/route");
            };
        };
        productChanges: {
            $id: {
                cancel: typeof import("@mercurjs/core/api/admin/product-changes/[id]/cancel/route");
                confirm: typeof import("@mercurjs/core/api/admin/product-changes/[id]/confirm/route");
            };
        };
        productOptions: typeof import("@medusajs/medusa/api/admin/product-options/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/product-options/[id]/route") & {
                values: typeof import("@medusajs/medusa/api/admin/product-options/[id]/values/route") & {
                    $valueId: typeof import("@medusajs/medusa/api/admin/product-options/[id]/values/[value_id]/route");
                };
            };
        };
        productTags: typeof import("@medusajs/medusa/api/admin/product-tags/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/product-tags/[id]/route");
        };
        productTypes: typeof import("@medusajs/medusa/api/admin/product-types/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/product-types/[id]/route");
        };
        productVariants: typeof import("@medusajs/medusa/api/admin/product-variants/route");
        products: typeof import("@mercurjs/core/api/admin/products/route") & {
            $id: typeof import("@mercurjs/core/api/admin/products/[id]/route") & {
                attributes: {
                    batch: typeof import("@mercurjs/core/api/admin/products/[id]/attributes/batch/route");
                };
                confirm: typeof import("@mercurjs/core/api/admin/products/[id]/confirm/route");
                images: {
                    $imageId: {
                        variants: {
                            batch: typeof import("@medusajs/medusa/api/admin/products/[id]/images/[image_id]/variants/batch/route");
                        };
                    };
                };
                options: typeof import("@medusajs/medusa/api/admin/products/[id]/options/route") & {
                    batch: typeof import("@medusajs/medusa/api/admin/products/[id]/options/batch/route");
                };
                preview: typeof import("@mercurjs/core/api/admin/products/[id]/preview/route");
                reject: typeof import("@mercurjs/core/api/admin/products/[id]/reject/route");
                requestChanges: typeof import("@mercurjs/core/api/admin/products/[id]/request-changes/route");
                sellers: typeof import("@mercurjs/core/api/admin/products/[id]/sellers/route");
                variants: typeof import("@mercurjs/core/api/admin/products/[id]/variants/route") & {
                    $variantId: typeof import("@mercurjs/core/api/admin/products/[id]/variants/[variant_id]/route") & {
                        images: {
                            batch: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/[variant_id]/images/batch/route");
                        };
                        inventoryItems: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/[variant_id]/inventory-items/route") & {
                            $inventoryItemId: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/[variant_id]/inventory-items/[inventory_item_id]/route");
                        };
                    };
                    batch: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/batch/route");
                    inventoryItems: {
                        batch: typeof import("@medusajs/medusa/api/admin/products/[id]/variants/inventory-items/batch/route");
                    };
                };
            };
            batch: typeof import("@medusajs/medusa/api/admin/products/batch/route");
            export: typeof import("@medusajs/medusa/api/admin/products/export/route");
            import: typeof import("@medusajs/medusa/api/admin/products/import/route") & {
                $transactionId: {
                    confirm: typeof import("@medusajs/medusa/api/admin/products/import/[transaction_id]/confirm/route");
                };
            };
            imports: typeof import("@medusajs/medusa/api/admin/products/imports/route") & {
                $transactionId: {
                    confirm: typeof import("@medusajs/medusa/api/admin/products/imports/[transaction_id]/confirm/route");
                };
            };
        };
        promotions: typeof import("@medusajs/medusa/api/admin/promotions/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/promotions/[id]/route") & {
                $ruleType: typeof import("@mercurjs/core/api/admin/promotions/[id]/[rule_type]/route");
                buyRules: {
                    batch: typeof import("@medusajs/medusa/api/admin/promotions/[id]/buy-rules/batch/route");
                };
                cost: typeof import("@mercurjs/core/api/admin/promotions/[id]/cost/route");
                rules: {
                    batch: typeof import("@medusajs/medusa/api/admin/promotions/[id]/rules/batch/route");
                };
                targetRules: {
                    batch: typeof import("@medusajs/medusa/api/admin/promotions/[id]/target-rules/batch/route");
                };
            };
            ruleAttributeOptions: {
                $ruleType: typeof import("@mercurjs/core/api/admin/promotions/rule-attribute-options/[rule_type]/route");
            };
            ruleValueOptions: {
                $ruleType: {
                    $ruleAttributeId: typeof import("@mercurjs/core/api/admin/promotions/rule-value-options/[rule_type]/[rule_attribute_id]/route");
                };
            };
        };
        propertyLabels: typeof import("@medusajs/medusa/api/admin/property-labels/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/property-labels/[id]/route");
            batch: typeof import("@medusajs/medusa/api/admin/property-labels/batch/route");
        };
        rbac: {
            me: {
                permissions: typeof import("@medusajs/medusa/api/admin/rbac/me/permissions/route");
            };
            policies: typeof import("@medusajs/medusa/api/admin/rbac/policies/route") & {
                $id: typeof import("@medusajs/medusa/api/admin/rbac/policies/[id]/route") & {
                    roles: typeof import("@medusajs/medusa/api/admin/rbac/policies/[id]/roles/route");
                };
                assignable: typeof import("@medusajs/medusa/api/admin/rbac/policies/assignable/route");
            };
            roles: typeof import("@medusajs/medusa/api/admin/rbac/roles/route") & {
                $id: typeof import("@medusajs/medusa/api/admin/rbac/roles/[id]/route") & {
                    policies: typeof import("@medusajs/medusa/api/admin/rbac/roles/[id]/policies/route") & {
                        $policyId: typeof import("@medusajs/medusa/api/admin/rbac/roles/[id]/policies/[policy_id]/route");
                    };
                    users: typeof import("@medusajs/medusa/api/admin/rbac/roles/[id]/users/route");
                };
                assignable: typeof import("@medusajs/medusa/api/admin/rbac/roles/assignable/route");
            };
        };
        refundReasons: typeof import("@medusajs/medusa/api/admin/refund-reasons/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/refund-reasons/[id]/route");
        };
        regions: typeof import("@medusajs/medusa/api/admin/regions/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/regions/[id]/route");
        };
        reservations: typeof import("@medusajs/medusa/api/admin/reservations/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/reservations/[id]/route");
        };
        returnReasons: typeof import("@medusajs/medusa/api/admin/return-reasons/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/return-reasons/[id]/route");
        };
        returns: typeof import("@medusajs/medusa/api/admin/returns/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/returns/[id]/route") & {
                cancel: typeof import("@medusajs/medusa/api/admin/returns/[id]/cancel/route");
                dismissItems: typeof import("@medusajs/medusa/api/admin/returns/[id]/dismiss-items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/returns/[id]/dismiss-items/[action_id]/route");
                };
                receive: typeof import("@medusajs/medusa/api/admin/returns/[id]/receive/route") & {
                    confirm: typeof import("@mercurjs/core/api/admin/returns/[id]/receive/confirm/route");
                };
                receiveItems: typeof import("@medusajs/medusa/api/admin/returns/[id]/receive-items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/returns/[id]/receive-items/[action_id]/route");
                };
                request: typeof import("@medusajs/medusa/api/admin/returns/[id]/request/route");
                requestItems: typeof import("@medusajs/medusa/api/admin/returns/[id]/request-items/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/returns/[id]/request-items/[action_id]/route");
                };
                shippingMethod: typeof import("@medusajs/medusa/api/admin/returns/[id]/shipping-method/route") & {
                    $actionId: typeof import("@medusajs/medusa/api/admin/returns/[id]/shipping-method/[action_id]/route");
                };
            };
        };
        salesChannels: typeof import("@medusajs/medusa/api/admin/sales-channels/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/sales-channels/[id]/route") & {
                products: typeof import("@medusajs/medusa/api/admin/sales-channels/[id]/products/route");
            };
        };
        sellers: typeof import("@mercurjs/core/api/admin/sellers/route") & {
            $id: typeof import("@mercurjs/core/api/admin/sellers/[id]/route") & {
                address: typeof import("@mercurjs/core/api/admin/sellers/[id]/address/route");
                approve: typeof import("@mercurjs/core/api/admin/sellers/[id]/approve/route");
                members: typeof import("@mercurjs/core/api/admin/sellers/[id]/members/route") & {
                    $memberId: typeof import("@mercurjs/core/api/admin/sellers/[id]/members/[member_id]/route");
                    invite: typeof import("@mercurjs/core/api/admin/sellers/[id]/members/invite/route");
                    invites: typeof import("@mercurjs/core/api/admin/sellers/[id]/members/invites/route") & {
                        $inviteId: typeof import("@mercurjs/core/api/admin/sellers/[id]/members/invites/[invite_id]/route") & {
                            resend: typeof import("@mercurjs/core/api/admin/sellers/[id]/members/invites/[invite_id]/resend/route");
                        };
                    };
                };
                paymentDetails: typeof import("@mercurjs/core/api/admin/sellers/[id]/payment-details/route");
                products: typeof import("@mercurjs/core/api/admin/sellers/[id]/products/route");
                professionalDetails: typeof import("@mercurjs/core/api/admin/sellers/[id]/professional-details/route");
                suspend: typeof import("@mercurjs/core/api/admin/sellers/[id]/suspend/route");
                terminate: typeof import("@mercurjs/core/api/admin/sellers/[id]/terminate/route");
                unsuspend: typeof import("@mercurjs/core/api/admin/sellers/[id]/unsuspend/route");
                unterminate: typeof import("@mercurjs/core/api/admin/sellers/[id]/unterminate/route");
            };
        };
        shippingOptionTypes: typeof import("@medusajs/medusa/api/admin/shipping-option-types/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/shipping-option-types/[id]/route");
        };
        shippingOptions: typeof import("@medusajs/medusa/api/admin/shipping-options/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/shipping-options/[id]/route") & {
                rules: {
                    batch: typeof import("@medusajs/medusa/api/admin/shipping-options/[id]/rules/batch/route");
                };
            };
        };
        shippingProfiles: typeof import("@medusajs/medusa/api/admin/shipping-profiles/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/shipping-profiles/[id]/route");
        };
        stockLocations: typeof import("@medusajs/medusa/api/admin/stock-locations/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/stock-locations/[id]/route") & {
                fulfillmentProviders: typeof import("@medusajs/medusa/api/admin/stock-locations/[id]/fulfillment-providers/route");
                fulfillmentSets: typeof import("@medusajs/medusa/api/admin/stock-locations/[id]/fulfillment-sets/route");
                salesChannels: typeof import("@medusajs/medusa/api/admin/stock-locations/[id]/sales-channels/route");
            };
        };
        stores: typeof import("@medusajs/medusa/api/admin/stores/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/stores/[id]/route");
        };
        taxProviders: typeof import("@medusajs/medusa/api/admin/tax-providers/route");
        taxRates: typeof import("@medusajs/medusa/api/admin/tax-rates/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/tax-rates/[id]/route") & {
                rules: typeof import("@medusajs/medusa/api/admin/tax-rates/[id]/rules/route") & {
                    $ruleId: typeof import("@medusajs/medusa/api/admin/tax-rates/[id]/rules/[rule_id]/route");
                };
            };
        };
        taxRegions: typeof import("@medusajs/medusa/api/admin/tax-regions/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/tax-regions/[id]/route");
        };
        translations: typeof import("@medusajs/medusa/api/admin/translations/route") & {
            batch: typeof import("@medusajs/medusa/api/admin/translations/batch/route");
            entities: typeof import("@medusajs/medusa/api/admin/translations/entities/route");
            settings: typeof import("@medusajs/medusa/api/admin/translations/settings/route") & {
                batch: typeof import("@medusajs/medusa/api/admin/translations/settings/batch/route");
            };
            statistics: typeof import("@medusajs/medusa/api/admin/translations/statistics/route");
        };
        uploads: typeof import("@medusajs/medusa/api/admin/uploads/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/uploads/[id]/route");
            presignedUrls: typeof import("@medusajs/medusa/api/admin/uploads/presigned-urls/route");
        };
        users: typeof import("@medusajs/medusa/api/admin/users/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/users/[id]/route") & {
                roles: typeof import("@medusajs/medusa/api/admin/users/[id]/roles/route") & {
                    $roleId: typeof import("@medusajs/medusa/api/admin/users/[id]/roles/[role_id]/route");
                };
            };
            me: typeof import("@mercurjs/core/api/admin/users/me/route");
        };
        views: {
            $entity: {
                columns: typeof import("@medusajs/medusa/api/admin/views/[entity]/columns/route");
                configurations: typeof import("@medusajs/medusa/api/admin/views/[entity]/configurations/route") & {
                    $id: typeof import("@medusajs/medusa/api/admin/views/[entity]/configurations/[id]/route");
                    active: typeof import("@medusajs/medusa/api/admin/views/[entity]/configurations/active/route");
                };
            };
            entities: typeof import("@medusajs/medusa/api/admin/views/entities/route");
        };
        workflowsExecutions: typeof import("@medusajs/medusa/api/admin/workflows-executions/route") & {
            $id: typeof import("@medusajs/medusa/api/admin/workflows-executions/[id]/route");
            $workflowId: {
                $transactionId: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/[transaction_id]/route") & {
                    subscribe: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/[transaction_id]/subscribe/route");
                };
                run: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/run/route");
                steps: {
                    failure: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/steps/failure/route");
                    success: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/steps/success/route");
                };
                subscribe: typeof import("@medusajs/medusa/api/admin/workflows-executions/[workflow_id]/subscribe/route");
            };
        };
        reviews: typeof import("@mercurjs/core/api/admin/reviews/route") & {
            $id: typeof import("@mercurjs/core/api/admin/reviews/[id]/route") & {
                respond: typeof import("@mercurjs/core/api/admin/reviews/[id]/respond/route");
            };
        };
    };
    auth: {
        $actorType: {
            $authProvider: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/route") & {
                callback: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/callback/route");
                register: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/register/route");
                resetPassword: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/reset-password/route");
                update: typeof import("@medusajs/medusa/api/auth/[actor_type]/[auth_provider]/update/route");
            };
        };
        mfa: {
            challenges: {
                $id: {
                    verify: typeof import("@medusajs/medusa/api/auth/mfa/challenges/[id]/verify/route");
                };
            };
            factors: typeof import("@medusajs/medusa/api/auth/mfa/factors/route") & {
                $id: typeof import("@medusajs/medusa/api/auth/mfa/factors/[id]/route") & {
                    verify: typeof import("@medusajs/medusa/api/auth/mfa/factors/[id]/verify/route");
                };
            };
            recoveryCodes: typeof import("@medusajs/medusa/api/auth/mfa/recovery-codes/route");
        };
        session: typeof import("@medusajs/medusa/api/auth/session/route");
        token: {
            refresh: typeof import("@medusajs/medusa/api/auth/token/refresh/route");
        };
        verification: {
            confirm: typeof import("@medusajs/medusa/api/auth/verification/confirm/route");
            request: typeof import("@medusajs/medusa/api/auth/verification/request/route");
        };
    };
};
